### ISSUE TITLE
.text section below image base

### ISSUE THREAD

**Issue by Atsika** [kyleavery/AceLdr#14]
Hi, there seems to be a problem while compiling AceLdr.

The error message is the following : 

```bin/AceLdr.x64.exe:.text: section below image base```

I tried with different version of mingw-gcc with both branches (main & gcc-10).

![image](https://user-images.githubusercontent.com/46649001/210561123-fd4b4cca-272b-4e33-9616-7cdd8471cb85.png)

![image](https://user-images.githubusercontent.com/46649001/210561450-7dfcb841-0278-4c67-a187-b4d5842f8428.png)

**Comment by HSIS007** [comment]
I have same issue

**Comment by kyleavery** [comment]
Should be fixed with `-Wl,--image-base=0`. Please reopen if you still have this issue.
