### ISSUE TITLE
Process dies when exit

### ISSUE THREAD

**Issue by vysecurity** [kyleavery/AceLdr#2]
Is the process death expected when you exit?

**Comment by kyleavery** [comment]
That probably isn't a good outcome in most scenarios. I will look into this and push a fix.

**Comment by kyleavery** [comment]
@vysecurity I just did a test where I injected into cmd.exe on 64-bit Windows 11. Executing the `exit` command in that Beacon's console did not kill the host process. Can you tell me more about the circumstances in which you encountered this bug so that I can replicate it?

**Comment by ScriptIdiot** [comment]
@kyleavery I did the same to inject to cmd.exe on 64-bit Windows 10. Process died when exit command was issued.
Besides, may I know if AceLdr does not support .NET execution? It also died when I tried to execute .NET in memory.
Thanks!

**Comment by kyleavery** [comment]
@ScriptIdiot I just tested 64-bit Windows 10 cmd.exe and the process did not exit. Did you use the example profile? If not, can you post your profile?

**Comment by kyleavery** [comment]
I am unable to replicate the issue on Windows 10 or 11 with cmd.exe or notepad.exe. If you continue to experience this behavior, reopen the issue and post your C2 profile and any debug information you can collect.

**Comment by vysecurity** [comment]
I’ll have another look, it might be related to the loader. Though it’s just
a basic loader that uses syscalls to inject into explorer.
